### ISSUE TITLE
Right clicking sign puts player in game 2 times

### ISSUE THREAD

**Issue by doglover129** [AddstarMC/BlockHunt#15]
When a player uses a sign to join an arena, it puts them in the game twice. With the @Steffion and your version. I am on the latest spigot for 1.8.9. Any idea why this may be happening? I am also using MV and Bungee cord. Thanks!

**Comment by addstar** [comment]
This doesn't happen with our version so I'm not sure it's caused by BlockHunt. Do some tests on a test server and remove other plugins that could be affecting it.
You can also use a really powerful tool called [WhatIs](http://jenkins.addstar.com.au/job/WhatIs/) to monitor which plugins handle the sign interaction.
